### ISSUE TITLE
compatibility problem with RFDuino

### ISSUE THREAD

**Issue by rmalka** [sparkfun/MS5803-14BA_Breakout#1]
Main problem: sensor breakout code uploads "successfully" to an RFDuino, but has no outputs on serial monitor (not even Serial.println("foo") after Serial.begin), making debugging/data collection difficult. 

I am using a Simblee RFD77201 with a SparkFun MS5803 14-bar pressure sensor. The code is (very slightly) modified from this breakout code (changed CELSIUS and FAHRENHEIT to CELSIUS1 and FAHRENHEIT1 in libraries and sketch because were already defined in RFD library), and is attached (libraries are MS5803_14.cpp and .h, modified sketch is PLEASEWORKPLEASE.ino). The RFD _does_ recognize the sensor at the correct address (0x76) when running an I2C device scanner (sketch attached as I2C_scanner.ino). The sensor is connected to the RFD as follows: SDA to GPIO6, SCL to GPIO5, GND to GND, +3V to +3V (using the USB shield so it's receiving 3.3V as it should). 

Thank you!

[files_RFDcompatibilityIssue.zip](https://github.com/sparkfun/MS5803-14BA_Breakout/files/209131/files_RFDcompatibilityIssue.zip)

**Comment by rmalka** [comment]
SOLUTION: 

(1) Go to the .cpp file (here, Sparkfun_MS5803_I2C.cpp) and comment out Wire.begin() (here, in the MS5803::MS5803(ms5803_addr address) function)

(2) In the sketch, insert Wire.begin() after the Serial.begin() line. It won't work before it.

**Comment by bboyho** [comment]
Hi,

I'm glad to hear that you got it working! I have updated the library [ [https://github.com/sparkfun/MS5803-14BA_Breakout](https://github.com/sparkfun/MS5803-14BA_Breakout) ] so that the I2C is initialized in the `setup()` instead of the library. Others seemed to be having the same issue regardless of the chip architecture. The example seemed to work regardless of `Wire.begin()` being before/after the `Serial.begin()`. The example works as long as it was initialized in the .ino file as opposed to the .cpp file.
